apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - task-maven.yaml
  - task-nodejs.yaml
  - task-spectral.yaml
  - task-microcks.yaml
  - task-image-tag-guard.yaml
  - enable-console-plugin.yaml
