apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: microcks-client
  namespace: tekton-tasks
spec:
  target:
    name: microcks-client
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client-secret: '{{ .clientSecret }}'
        microcks-url: '{{ $target := .platformConfig | fromYaml }}{{ $target.spec.platform.services.microcks.url }}'
  data:
    - secretKey: platformConfig
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-config}}
      remoteRef: {key: platform-target-config, property: platform.yaml}
    - secretKey: clientSecret
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-secrets}}
      remoteRef: {key: platform-secrets, property: KEYCLOAK_MICROCKS_CLIENT_SECRET}
