apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-infrastructure
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '-30'
spec:
  description: Bootstrap secrets and shared platform infrastructure
  sourceRepos:
  - https://github.com/contract-first-idp/platform-components.git
  destinations:
  - server: https://kubernetes.default.svc
    namespace: cf-idp-secrets
  clusterResourceWhitelist:
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: external-secrets.io
    kind: ClusterSecretStore
  - group: operator.openshift.io
    kind: ExternalSecretsConfig
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
