apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-realm-secrets
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  target:
    name: keycloak-realm-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        backstage-client-secret: '{{ .backstageClientSecret }}'
        microcks-client-secret: '{{ .microcksClientSecret }}'
        demo-user-password: '{{ .demoUserPassword }}'
        developer-hub-url: '{{ $target := .platformConfig | fromYaml }}{{ $target.spec.platform.services.developerHub.url }}'
        developer-hub-oidc-callback: '{{ $target := .platformConfig | fromYaml }}{{ $target.spec.platform.services.developerHub.oidcCallbackUrl }}'
        microcks-url: '{{ $target := .platformConfig | fromYaml }}{{ $target.spec.platform.services.microcks.url }}'
        microcks-redirect-uri: '{{ $target := .platformConfig | fromYaml }}{{ $target.spec.platform.services.microcks.redirectUri }}'
  data:
    - secretKey: platformConfig
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-config}}
      remoteRef: {key: platform-target-config, property: platform.yaml}
    - secretKey: backstageClientSecret
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-secrets}}
      remoteRef: {key: platform-secrets, property: KEYCLOAK_BACKSTAGE_CLIENT_SECRET}
    - secretKey: microcksClientSecret
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-secrets}}
      remoteRef: {key: platform-secrets, property: KEYCLOAK_MICROCKS_CLIENT_SECRET}
    - secretKey: demoUserPassword
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-secrets}}
      remoteRef: {key: platform-secrets, property: DEMO_USER_PASSWORD}
