apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: microcks-mongodb-connection
  namespace: microcks
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  secretStoreRef:
    name: cf-idp-secrets
    kind: ClusterSecretStore
  target:
    name: microcks-mongodb-connection
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - {secretKey: username, remoteRef: {key: platform-secrets, property: MICROCKS_MONGODB_USERNAME}}
    - {secretKey: password, remoteRef: {key: platform-secrets, property: MICROCKS_MONGODB_PASSWORD}}
    - {secretKey: adminUsername, remoteRef: {key: platform-secrets, property: MICROCKS_MONGODB_ADMIN_USERNAME}}
    - {secretKey: adminPassword, remoteRef: {key: platform-secrets, property: MICROCKS_MONGODB_ADMIN_PASSWORD}}
