apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: microcks-mongodb-connection
  namespace: microcks
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  secretStoreRef:
    name: cf-idp-secrets
    kind: ClusterSecretStore
  target:
    name: microcks-mongodb-connection
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: microcks
        adminUsername: admin
        password: '{{ .password }}'
        adminPassword: '{{ .adminPassword }}'
  data:
    - {secretKey: password, remoteRef: {key: platform-generated-secrets, property: MICROCKS_MONGODB_PASSWORD}}
    - {secretKey: adminPassword, remoteRef: {key: platform-generated-secrets, property: MICROCKS_MONGODB_ADMIN_PASSWORD}}
