kind: ConfigMap
apiVersion: v1
metadata:
  name: "microcks-mongodb-init"
  labels:
    app: "microcks"
    container: mongodb
    group: microcks

  annotations:

data:
  create-user.sh: |-
    #!/bin/bash
    echo "Started Adding the Users..."
    mongo admin --eval "db.getSiblingDB('${MONGO_INITDB_DATABASE}').createUser({user: '${MONGODB_USER}', pwd: '${MONGODB_PASSWORD}', roles: [{role: 'readWrite', db: '${MONGO_INITDB_DATABASE}'}]})"
    echo "End Adding the User Roles."
