apiVersion: v1
kind: ServiceAccount
metadata:
  name: cf-idp-config-reader
  namespace: cf-idp-secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cf-idp-credential-reader
  namespace: cf-idp-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cf-idp-config-reader
  namespace: cf-idp-secrets
rules:
  - apiGroups: ['']
    resources: [secrets]
    resourceNames: [platform-target-config]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cf-idp-credential-reader
  namespace: cf-idp-secrets
rules:
  - apiGroups: ['']
    resources: [secrets]
    resourceNames: [platform-secrets, platform-generated-secrets]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cf-idp-config-reader
  namespace: cf-idp-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cf-idp-config-reader
subjects:
  - kind: ServiceAccount
    name: cf-idp-config-reader
    namespace: cf-idp-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cf-idp-credential-reader
  namespace: cf-idp-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cf-idp-credential-reader
subjects:
  - kind: ServiceAccount
    name: cf-idp-credential-reader
    namespace: cf-idp-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cf-idp-secret-reader-review
rules:
  - apiGroups: [authorization.k8s.io]
    resources: [selfsubjectrulesreviews]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cf-idp-secret-reader-review
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cf-idp-secret-reader-review
subjects:
  - kind: ServiceAccount
    name: cf-idp-config-reader
    namespace: cf-idp-secrets
  - kind: ServiceAccount
    name: cf-idp-credential-reader
    namespace: cf-idp-secrets
