apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant-cf-idp-tenant-admission
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  description: Parent Domain attachment for cf-idp-tenant.
  sourceRepos:
    - https://github.com/contract-first-idp-test/developer-charts.git
    - https://github.com/contract-first-idp-test/cf-idp-tenant-domain.git
    - https://github.com/contract-first-idp-test/platform-components.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: openshift-gitops
  namespaceResourceWhitelist:
    - {group: argoproj.io, kind: AppProject}
    - {group: argoproj.io, kind: ApplicationSet}
