kind: ConfigMap
apiVersion: v1
metadata:
  name: demo-domain
data:
  catalog-info.yaml: |-
    apiVersion: backstage.io/v1alpha1
    kind: Domain
    metadata:
      name: demo
      description: Domain for demo systems
      labels:
        cluster-domain: {{ .Values.clusterRouterDomain }}
        git-org: {{ .Values.git.org }}
        artifact-group: com.redhat.demo
    spec:
      owner: backstage-admins
