kind: Secret
apiVersion: v1
metadata:
  name: rhdh-secrets
stringData:
  BACKEND_SECRET: replaceme
  KEYCLOAK_BASE_URL: "{{ .Values.auth.keycloakUrl }}"
  KEYCLOAK_REALM: "{{ .Values.auth.keycloakRealm }}"
  KEYCLOAK_CLIENT_ID: "{{ .Values.auth.clientId }}"
  KEYCLOAK_CLIENT_SECRET: "{{ .Values.auth.clientSecret }}"
  GIT_TOKEN: "{{ .Values.git.token }}"
  K8S_CLUSTER_NAME: "development-cluster"
  K8S_CLUSTER_URL: "https://{{ .Values.clusterApiDomain }}:6443"
type: Opaque