apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: "{{ .Values.gitHost }}/{{ .Values.gitOrg }}/platform-components.git"
    path: charts/developer-hub
    targetRevision: "{{ .Values.gitRef }}"
    helm:
      parameters:
        - name: "clusterRouterDomain"
          value: "{{ .Values.clusterRouterDomain }}"
        - name: "clusterApiDomain"
          value: {{ .Values.clusterRouterDomain | replace "apps" "api" }}
        - name: "auth.sessionSecret"
          value: "{{ .Values.authClientSecret }}"
        - name: "auth.keycloakUrl"
          value: "https://keycloak.{{ .Values.clusterRouterDomain }}"
        - name: "auth.keycloakRealm"
          value: backstage
        - name: "auth.clientId"
          value: backstage
        - name: "auth.clientSecret"
          value: "{{ .Values.authClientSecret }}"
        - name: "git.org"
          value: "{{ .Values.gitOrg }}"
        - name: "git.token"
          value: "{{ .Values.gitToken }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: developer-hub
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 10m
