apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio
spec:
  dnsNames:
    - minio
    - minio.minio.svc.cluster.local
    - "minio-minio.{{ .Values.clusterRouterDomain }}"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: global-issuer
  secretName: "{{ .Values.minioTlsSecret }}"
  usages:
    - server auth