apiVersion: v1
kind: Secret
metadata:
  name: minio-configuration
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="{{ .Values.minioUser }}"
    export MINIO_ROOT_PASSWORD="{{ .Values.minioPassword }}"
    export MINIO_BROWSER="on"