apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: {name: gitea-config, namespace: gitea}
spec:
  target:
    name: gitea-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ROOT_URL: '{{ $target := .platformConfig | fromYaml }}{{ $target.spec.platform.services.gitea.rootUrl }}'
        DOMAIN: '{{ $target := .platformConfig | fromYaml }}{{ $target.spec.platform.services.gitea.domain }}'
        SSH_DOMAIN: '{{ $target := .platformConfig | fromYaml }}{{ $target.spec.platform.services.gitea.sshDomain }}'
  data:
    - secretKey: platformConfig
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-config}}
      remoteRef: {key: platform-target-config, property: platform.yaml}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: {name: gitea-secrets, namespace: gitea}
spec:
  target: {name: gitea-secrets, creationPolicy: Owner}
  data:
    - secretKey: SECRET_KEY
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-secrets}}
      remoteRef: {key: platform-generated-secrets, property: GITEA_SECRET_KEY}
    - secretKey: INTERNAL_TOKEN
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-secrets}}
      remoteRef: {key: platform-generated-secrets, property: GITEA_INTERNAL_TOKEN}
    - secretKey: JWT_SECRET
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-secrets}}
      remoteRef: {key: platform-generated-secrets, property: GITEA_JWT_SECRET}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: {name: gitea-admin, namespace: gitea}
spec:
  target: {name: gitea-admin, creationPolicy: Owner}
  data:
    - secretKey: username
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-secrets}}
      remoteRef: {key: platform-secrets, property: GITEA_ADMIN_USERNAME}
    - secretKey: password
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-secrets}}
      remoteRef: {key: platform-generated-secrets, property: GITEA_ADMIN_PASSWORD}
    - secretKey: email
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-secrets}}
      remoteRef: {key: platform-secrets, property: GITEA_ADMIN_EMAIL}
