apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: gitea-db
  namespace: gitea
spec:
  postgresVersion: 16
  instances:
    - name: postgres
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  users:
    - name: postgres
      databases:
        - gitea
      password:
        type: AlphaNumeric
