apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-oauth-config
  namespace: openshift-devspaces
spec:
  secretStoreRef:
    name: cf-idp-secrets
    kind: ClusterSecretStore
  target:
    name: github-oauth-config
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/part-of: che.eclipse.org
          app.kubernetes.io/component: oauth-scm-configuration
        annotations:
          che.eclipse.org/oauth-scm-server: github
          che.eclipse.org/scm-server-endpoint: https://github.com/
      data:
        id: '{{ .clientId }}'
        secret: '{{ .clientSecret }}'
      engineVersion: v2
  data:
  - secretKey: clientId
    remoteRef:
      key: platform-secrets
      property: GITHUB_APP_CLIENT_ID
  - secretKey: clientSecret
    remoteRef:
      key: platform-secrets
      property: GITHUB_APP_CLIENT_SECRET
