apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: openshift-gitops
spec:
  project: platform-services
  destination: {server: https://kubernetes.default.svc, namespace: gitea}
  source:
    repoURL: https://github.com/contract-first-idp/platform-components.git
    targetRevision: main
    path: components/gitea
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [RespectIgnoreDifferences=true, CreateNamespace=true, SkipDryRunOnMissingResource=true]
