apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipelines
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '5'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-services
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-tasks
  source:
    repoURL: https://github.com/contract-first-idp/platform-components.git
    targetRevision: main
    path: components/pipelines
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
    - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 1m
