apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rhdh-secrets
  namespace: developer-hub
spec:
  target:
    name: rhdh-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        BACKSTAGE_BACKEND_SECRET: '{{ .backstageBackendSecret }}'
        GITHUB_HOST: '{{ $target := .platformConfig | fromYaml }}{{ $target.spec.platform.configuration.host }}'
        GITHUB_APP_ID: '{{ .githubAppId }}'
        GITHUB_APP_CLIENT_ID: '{{ .githubAppClientId }}'
        GITHUB_APP_CLIENT_SECRET: '{{ .githubAppClientSecret }}'
        GITHUB_APP_PRIVATE_KEY: '{{ .githubAppPrivateKeyBase64 | b64dec }}'
        SOFTWARE_TEMPLATES_CATALOG_URL: >-
          {{- $target := .platformConfig | fromYaml -}}
          {{- $dependency := $target.spec.platform.dependencies.softwareTemplates -}}
          {{- $repositoryUrl := urlParse $dependency.repositoryUrl -}}
          {{- $repositoryPath := regexReplaceAll "/+" $repositoryUrl.path "/" | trimSuffix "/" | trimSuffix ".git" -}}
          {{- $catalogPath := regexReplaceAll "/+" $dependency.catalogPath "/" | trimAll "/" -}}
          {{- printf "%s://%s%s/blob/%s/%s" $repositoryUrl.scheme $repositoryUrl.host $repositoryPath $dependency.revision $catalogPath -}}
        GITHUB_CATALOG_REPOSITORY_FILTER: >-
          {{- $target := .platformConfig | fromYaml -}}
          {{- $dependency := $target.spec.platform.dependencies.softwareTemplates -}}
          {{- if and (eq (lower $target.spec.platform.configuration.host) (lower $dependency.host)) (eq (lower $target.spec.platform.configuration.organization) (lower $dependency.organization)) -}}
          {{- printf "^(?!%s$).*$" (regexQuoteMeta $dependency.repository) -}}
          {{- else -}}
          .*
          {{- end -}}
        KEYCLOAK_CLIENT_ID: backstage
        KEYCLOAK_CLIENT_SECRET: '{{ .keycloakClientSecret }}'
        KEYCLOAK_REALM: platform
        K8S_CLUSTER_NAME: '{{ $target := .platformConfig | fromYaml }}{{ $target.spec.platform.cluster.name }}'
        DEVELOPER_HUB_URL: '{{ $target := .platformConfig | fromYaml }}{{ $target.spec.platform.services.developerHub.url }}'
        SCHEMA_REGISTRY_HOST: '{{ $target := .platformConfig | fromYaml }}{{ $registry := urlParse $target.spec.platform.schemaRegistry.apiUrl }}{{ $registry.host }}'
        KEYCLOAK_BASE_URL: '{{ $target := .platformConfig | fromYaml }}{{ $target.spec.platform.services.keycloak.url }}'
  data:
    - secretKey: platformConfig
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-config}}
      remoteRef: {key: platform-target-config, property: platform.yaml}
    - secretKey: backstageBackendSecret
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-secrets}}
      remoteRef: {key: platform-generated-secrets, property: BACKSTAGE_BACKEND_SECRET}
    - secretKey: githubAppId
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-secrets}}
      remoteRef: {key: platform-secrets, property: GITHUB_APP_ID}
    - secretKey: githubAppClientId
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-secrets}}
      remoteRef: {key: platform-secrets, property: GITHUB_APP_CLIENT_ID}
    - secretKey: githubAppClientSecret
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-secrets}}
      remoteRef: {key: platform-secrets, property: GITHUB_APP_CLIENT_SECRET}
    - secretKey: githubAppPrivateKeyBase64
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-secrets}}
      remoteRef: {key: platform-secrets, property: GITHUB_APP_PRIVATE_KEY_BASE64}
    - secretKey: keycloakClientSecret
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-secrets}}
      remoteRef: {key: platform-generated-secrets, property: KEYCLOAK_BACKSTAGE_CLIENT_SECRET}
