apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rhdh-secrets
  namespace: developer-hub
spec:
  target:
    name: rhdh-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        BACKEND_SECRET: '{{ .backendSecret }}'
        GITHUB_TOKEN: '{{ .githubToken }}'
        GITHUB_ORG: '{{ .githubOrg }}'
        GITHUB_HOST: '{{ .githubHost }}'
        KEYCLOAK_REALM: '{{ .keycloakRealm }}'
        KEYCLOAK_CLIENT_ID: '{{ .keycloakClientId }}'
        KEYCLOAK_CLIENT_SECRET: '{{ .keycloakClientSecret }}'
        K8S_CLUSTER_NAME: '{{ .clusterName }}'
        K8S_CLUSTER_URL: '{{ .clusterApiUrl }}'
        DEVELOPER_HUB_URL: '{{ $target := .platformConfig | fromYaml }}{{ $target.spec.platform.services.developerHub.url }}'
        SCHEMA_REGISTRY_HOST: '{{ $target := .platformConfig | fromYaml }}{{ $registry := urlParse $target.spec.platform.schemaRegistry.apiUrl }}{{ $registry.host }}'
        KEYCLOAK_BASE_URL: '{{ $target := .platformConfig | fromYaml }}{{ $target.spec.platform.services.keycloak.url }}'
        SOFTWARE_TEMPLATES_CATALOG_URL: '{{ trimSuffix ".git" .softwareTemplatesRepoUrl }}/blob/{{ .softwareTemplatesRevision }}/{{ .softwareTemplatesCatalogPath }}'
        PLATFORM_TARGET_CATALOG_URL: '{{ trimSuffix ".git" .platformRepoUrl }}/blob/{{ .platformConfigRevision }}/{{ .platformTargetCatalogPath }}'
  data:
    - secretKey: platformConfig
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-config}}
      remoteRef: {key: platform-target-config, property: platform.yaml}
    - secretKey: githubHost
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-config}}
      remoteRef: {key: platform-bootstrap-config, property: GITHUB_HOST}
    - secretKey: githubOrg
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-config}}
      remoteRef: {key: platform-bootstrap-config, property: GITHUB_ORG}
    - secretKey: clusterName
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-config}}
      remoteRef: {key: platform-bootstrap-config, property: CLUSTER_NAME}
    - secretKey: clusterApiUrl
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-config}}
      remoteRef: {key: platform-bootstrap-config, property: CLUSTER_API_URL}
    - secretKey: softwareTemplatesRepoUrl
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-config}}
      remoteRef: {key: platform-bootstrap-config, property: SOFTWARE_TEMPLATES_REPO_URL}
    - secretKey: softwareTemplatesRevision
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-config}}
      remoteRef: {key: platform-bootstrap-config, property: SOFTWARE_TEMPLATES_REVISION}
    - secretKey: softwareTemplatesCatalogPath
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-config}}
      remoteRef: {key: platform-bootstrap-config, property: SOFTWARE_TEMPLATES_CATALOG_PATH}
    - secretKey: platformRepoUrl
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-config}}
      remoteRef: {key: platform-bootstrap-config, property: PLATFORM_REPO_URL}
    - secretKey: platformConfigRevision
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-config}}
      remoteRef: {key: platform-bootstrap-config, property: PLATFORM_CONFIG_REVISION}
    - secretKey: platformTargetCatalogPath
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-config}}
      remoteRef: {key: platform-bootstrap-config, property: PLATFORM_TARGET_CATALOG_PATH}
    - secretKey: keycloakRealm
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-config}}
      remoteRef: {key: platform-bootstrap-config, property: KEYCLOAK_REALM}
    - secretKey: keycloakClientId
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-config}}
      remoteRef: {key: platform-bootstrap-config, property: KEYCLOAK_CLIENT_ID}
    - secretKey: backendSecret
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-secrets}}
      remoteRef: {key: platform-secrets, property: BACKEND_SECRET}
    - secretKey: githubToken
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-secrets}}
      remoteRef: {key: platform-secrets, property: GITHUB_TOKEN}
    - secretKey: keycloakClientSecret
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-secrets}}
      remoteRef: {key: platform-secrets, property: KEYCLOAK_BACKSTAGE_CLIENT_SECRET}
