apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rhdh-secrets
  namespace: developer-hub
spec:
  target:
    name: rhdh-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        BACKEND_SECRET: '{{ .backendSecret }}'
        GITHUB_TOKEN: '{{ .githubToken }}'
        GITHUB_ORG: '{{ $target := .platformConfig | fromYaml }}{{ $target.spec.platform.configuration.organization }}'
        GITHUB_HOST: '{{ $target := .platformConfig | fromYaml }}{{ $target.spec.platform.configuration.host }}'
        KEYCLOAK_CLIENT_SECRET: '{{ .keycloakClientSecret }}'
        K8S_CLUSTER_NAME: '{{ $target := .platformConfig | fromYaml }}{{ $target.spec.platform.cluster.name }}'
        K8S_CLUSTER_URL: '{{ $target := .platformConfig | fromYaml }}{{ $target.spec.platform.cluster.apiUrl }}'
        DEVELOPER_HUB_URL: '{{ $target := .platformConfig | fromYaml }}{{ $target.spec.platform.services.developerHub.url }}'
        SCHEMA_REGISTRY_HOST: '{{ $target := .platformConfig | fromYaml }}{{ $registry := urlParse $target.spec.platform.schemaRegistry.apiUrl }}{{ $registry.host }}'
        KEYCLOAK_BASE_URL: '{{ $target := .platformConfig | fromYaml }}{{ $target.spec.platform.services.keycloak.url }}'
  data:
    - secretKey: platformConfig
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-config}}
      remoteRef: {key: platform-target-config, property: platform.yaml}
    - secretKey: backendSecret
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-secrets}}
      remoteRef: {key: platform-secrets, property: BACKEND_SECRET}
    - secretKey: githubToken
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-secrets}}
      remoteRef: {key: platform-secrets, property: GITHUB_TOKEN}
    - secretKey: keycloakClientSecret
      sourceRef: {storeRef: {kind: ClusterSecretStore, name: cf-idp-secrets}}
      remoteRef: {key: platform-secrets, property: KEYCLOAK_BACKSTAGE_CLIENT_SECRET}
