apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - external-secret.yaml
  - serviceaccount.yaml
  - dynamic-plugins.yaml
  - app-config.yaml
  - backstage.yaml
configMapGenerator:
  - name: cf-idp-compatibility-action
    namespace: developer-hub
    files:
      - compatibility-action/package.json
      - compatibility-action/index.cjs.js
      - compatibility-action/compatibility.cjs
generatorOptions:
  disableNameSuffixHash: true
