apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry3
metadata:
  name: apicurio-registry
  namespace: apicurio
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    platform.contract-first.io/router-domain: example.invalid
spec:
  app:
    storage:
      type: postgresql
      sql:
        dataSource:
          url: jdbc:postgresql://apicurio-db-primary:5432/apicurio
          username: apicurio
          password:
            name: apicurio-db-pguser-apicurio
            key: password
    ingress:
      enabled: true
      host: apicurio.invalid
      ingressClassName: openshift-default
      annotations:
        route.openshift.io/termination: edge
  ui:
    env:
      - name: REGISTRY_API_URL
        value: https://replace.invalid/apis/registry/v3
    ingress:
      enabled: true
      host: apicurio-ui.invalid
      ingressClassName: openshift-default
      annotations:
        route.openshift.io/termination: edge
