apiVersion: v1
kind: ConfigMap
metadata:
  name: apicurio-db-init
  namespace: apicurio
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
data:
  init.sql: '\connect apicurio

    GRANT USAGE, CREATE ON SCHEMA public TO apicurio;

    '
